apiVersion: v2
name: ${project.name}
version: ${project.version}
appVersion: ${project.version}
description: ${project.name}
keywords:
  - ${project.name}
  - angular
  - onecx
sources:
  - https://github.com/onecx-apps/${project.name}
maintainers:
  - name: Tkit Developer
    email: tkit_dev@1000kit.org
dependencies:
  - name: helm-angular-app
    alias: app
    version: ^0
    repository: oci://ghcr.io/onecx/charts
